# required dependencies

- name: make sure epel-release is installed
  yum:
    name: "{{ item }}"
    state: present
    lock_timeout: 180
  become: yes
  with_items:
    - epel-release
    - rsync
    - unzip
    - psmisc


- name: Add nginx repository
  yum_repository:
    name: nginx
    description: Nginx YUM repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
    enabled: yes
    state: present
  become: yes

- name: "make sure nginx {{ nginx_version }} is installed"
  yum:
    name: "nginx-{{ nginx_version }}"
    state: present
    lock_timeout: 180
  become: yes

# disable selinux and firewalld

- name: disable selinux
  selinux:
    state: disabled
  become: yes
   
- name: stop and disable firewall     # ? need to discuss on disabling firewall service ?
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  become: yes
  ignore_errors: yes
  with_items:
    - firewalld